title: "Operating Systems 2021-1 (OS211)"
copyright: "2021-2021"

author: "frsardhf"
address: "jkt"
sitemap: "true"

urlweb: "https://frsardhf.github.io/os211/"
urlgithub: "https://github.com/frsardhf/os211/"
urlghpage: "https://frsardhf.github.io/os211/"
github: [metadata]
